spring.application.name=user-service

# Neon PostgreSQL
spring.datasource.url=jdbc:postgresql://ep-fancy-surf-a1v377af-pooler.ap-southeast-1.aws.neon.tech:5432/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_Ow8ru2dZoXSD
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
