spring.application.name=plant-service
server.port=8081

#Neon PostgreSQL
spring.datasource.url=jdbc:postgresql://ep-fancy-surf-a1v377af-pooler.ap-southeast-1.aws.neon.tech/plantDB?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_Ow8ru2dZoXSD
spring.datasource.driver-class-name=org.postgresql.Driver

# JWT (same secret as user-service so tokens issued there are valid here)
jwt.secret=your-256-bit-secret-change-in-production-make-it-long-enough

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true